export const daerah = {
  Johor: [
    "Batu Pahat",
    "Johor Bahru",
    "Kluang",
    "Kota Tinggi",
    "Kulai",
    "Tangkak",
    "Mersing",
    "Muar",
    "Pontian",
    "Segamat",
  ],

  Kedah: [
    "Kota Setar",
    "Kuala Muda",
    "Kubang Pasu",
    "Kulim",
    "Langkawi",
    "Pokok Sena",
    "Pendang",
    "Bandar Baharu",
    "Yan",
    "Padang Terap",
    "Baling",
    "Sik",
  ],

  Kelantan: [
    "Kota Bharu",
    "Tumpat",
    "Pasir Mas",
    "Pasir Puteh",
    "Bachok",
    "Machang",
    "Jeli",
    "Tanah Merah",
    "Kuala Krai",
    "Gua Musang",
    "Lojing",
  ],

  Melaka: ["Melaka Tengah", "Alor Gajah", "Jasin"],
  "Negeri Sembilan": [
    "Seremban",
    "Jempol",
    "Port Dickson",
    "Tampin",
    "Kuala Pilah",
    "Rembau",
    "Jelebu",
  ],

  Pahang: [
    "Pekan",
    "Kuantan",
    "Rompin",
    "Maran",
    "Bera",
    "Jerantut",
    "Temerloh",
    "Raub",
    "Lipis",
    "Cameron Higlands",
  ],

  Perak: [
    "Batang Padang",
    "Manjung",
    "Kinta",
    "Kerian",
    "Kuala Kangsar",
    "Larut & Matang",
    "Hilir Perak",
    "Hulu Perak",
    "Perak Tengah",
  ],

  Perlis: ["Perlis"],

  "Pulau Pinang": [
    "Barat Daya",
    "Seberang Perai Selatan",
    "Seberang Perai Tengah",
    "Seberang Perai Utara",
    "Timur Laut",
  ],

  Sabah: [
    "Kota Marudu",
    "Kudat",
    "Pitas",
    "Kota Belud",
    "Kota Kinabalu",
    "Papar",
    "Penampang",
    "Putatan",
    "Ranau",
    "Tuaran",
    "Beaufort",
    "Keningau",
    "Kuala Penyu",
    "Nabawan",
    "Sipitang",
    "Tambunan",
    "Tenom",
    "Beluran",
    "Kinabatangan",
    "Sandakan",
    "Tongod",
    "Kunak",
    "Lahad Datu",
    "Semporna",
    "Tawau",
  ],

  Sarawak: [
    "Lundu",
    "Bau",
    "Serian",
    "Tebedu",
    "Siburan",
    "Samarahan",
    "Asajaya",
    "Simunjan",
    "Sebuyau",
    "Gedong",
    "Sri Aman",
    "Lubok Antu",
    "Pantu",
    "Lingga",
    "Betong",
    "Saratok",
    "Kabong",
    "Pusa",
    "Sarikei",
    "Maradong",
    "Julau",
    "Pakan",
    "Sibu",
    "Kanowit",
    "Selangau",
    "Mukah",
    "Dalat",
    "Matu",
    "Daro",
    "Tanjung Manis",
    "Kapit",
    "Song",
    "Belaga",
    "Bukit Mabong",
    "Bintulu",
    "Tatau",
    "Sebauh",
    "Miri",
    "Marudi",
    "Subis",
    "Beluru",
    "Telang Usan",
    "Limbang",
    "Lawas",
  ],

  Selangor: [
    "Petaling",
    "Klang",
    "Gombak",
    "Hulu Langat",
    "Kuala Langat",
    "Hulu Selangor",
    "Kuala Selangor",
    "Sabak Bernam",
    "Sepang",
  ],
  Terengganu: [
    "Kuala Terengganu",
    "Kemaman",
    "Dungun",
    "Marang",
    "Hulu Terengganu",
    "Besut",
  ],
  KualaLumpur: ["Kuala Lumpur"],
  Putrajaya: ["Putrajaya"],
  Labuan: ["Labuan"],
  Wilayah: ["Kuala Lumpur", "Putrajaya" /* "Labuan" */],
};

/* export const Johor = [
  "Batu Pahat",
  "Johor Bahru",
  "Kluang",
  "Kota Tinggi",
  "Kulai",
  "Tangkak",
  "Mersing",
  "Muar",
  "Pontian",
  "Segamat",
];

export const Kedah = [
  "Kota Setar",
  "Kuala Muda",
  "Kubang Pasu",
  "Kulim",
  "Langkawi",
  "Pokok Sena",
  "Pendang",
  "Bandar Baharu",
  "Yan",
  "Padang Terap",
  "Baling",
  "Sik",
];

const Kelantan = [
  "Kota Bharu",
  "Tumpat",
  "Pasir Mas",
  "Pasir Puteh",
  "Bachok",
  "Machang",
  "Jeli",
  "Tanah Merah",
  "Kuala Krai",
  "Gua Musang",
  "Lojing",
];

const Melaka = ["Melaka Tengah", "Alor Gajah", "Jasin"];
const NegeriSembilan = [
  "Seremban",
  "Jempoi",
  "Port Dickson",
  "Tampin",
  "Kuala Pilah",
  "Rembau",
  "Jelebu",
];

const Pahang = [
  "Pekan",
  "Kuantan",
  "Rompin",
  "Maran",
  "Bera",
  "Jerantut",
  "Temerloh",
  "Raub",
  "Lipis",
  "Cameron Higlands",
];

const Perak = [
  "Batang Padang",
  "Manjung",
  "Kinta",
  "Kerian",
  "Kuala Kangsar",
  "Larut & Matang",
  "Hilir Perak",
  "Ulu Perak",
  "Perak Tengah",
];

const Perlis = [""];

const PulauPinang = [
  "Barat Daya",
  "Seberang Perai Selatan",
  "Seberang Perai Tengah",
  "Seberang Perai Utara",
  "Timur Laut",
];

const Sabah = [
  "Kota Marudu",
  "Kudat",
  "Pitas",
  "Kota Belud",
  "Kota Kinabalu",
  "Papar",
  "Penampang",
  "Putatan",
  "Ranau",
  "Tuaran",
  "Beaufort",
  "Keningau",
  "Kuala Penyu",
  "Nabawan",
  "Sipitang",
  "Tambunan",
  "Tenom",
  "Beluran",
  "Kinabatangan",
  "Sandakan",
  "Tongod",
  "Kunak",
  "Lahad Datu",
  "Semporna",
  "Tawau",
];

const Sarawak = [
  "Lundu",
  "Bau",
  "Serian",
  "Tebedu",
  "Siburan",
  "Samarahan",
  "Asajaya",
  "Simunjan",
  "Sebuyau",
  "Gedong",
  "Sri Aman",
  "Lubok Antu",
  "Pantu",
  "Lingga",
  "Betong",
  "Saratok",
  "Kabong",
  "Pusa",
  "Sarikei",
  "Maradong",
  "Julau",
  "Pakan",
  "Sibu",
  "Kanowit",
  "Selangau",
  "Mukah",
  "Dalat",
  "Matu",
  "Daro",
  "Tanjung Manis",
  "Kapit",
  "Song",
  "Belaga",
  "Bukit Mabong",
  "Bintulu",
  "Tatau",
  "Sebauh",
  "Miri",
  "Marudi",
  "Subis",
  "Beluru",
  "Telang Usan",
  "Limbang",
  "Lawas",
];

const Selangor = [
  "Petaling",
  "Klang",
  "Gombak",
  "Hulu Langat",
  "Kuala Langat",
  "Hulu Selangor",
  "Kuala Selangor",
  "Sabak Bernam",
  "Sepang",
];
const Terengganu = [
  "Kuala Terengganu",
  "Kemaman",
  "Dungun",
  "Marang",
  "Hulu Terengganu",
  "Besut",
];

const KualaLumpur = [""];
const Putrajaya = [""];
const Labuan = [""];
 */
