import { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import tailwind from "tailwindcss";
import Navi from "./navi";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="white">
        <Navi />
        {/* Layout UI */}
        <main>{children}</main>
      </body>
    </html>
  );
}
